version: '3.3' 
services:
    web: 
        image: php:7.4-apache 
        container_name: php74
        volumes:
        - ./php:/var/www/html/ 
        ports: 
        - 80:80



curl -s https://laravel.build/example-app | bash